//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store_part3 {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl products;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor im1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl product1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl des1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl price1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form3;
		
		protected System.Web.UI.WebControls.Button button5;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor im2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl product2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl des2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl price2;
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.Button button2;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor im3;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl product3;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl des3;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl price3;
		
		protected System.Web.UI.HtmlControls.HtmlForm form4;
		
		protected System.Web.UI.WebControls.Button button4;
		
		protected System.Web.UI.HtmlControls.HtmlForm form5;
		
		protected System.Web.UI.WebControls.Button button6;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor im4;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl product4;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl des4;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl price4;
		
		protected System.Web.UI.HtmlControls.HtmlForm form6;
		
		protected System.Web.UI.WebControls.Button button7;
	}
}
