//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store_part3 {
	
	
	public partial class edit {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlSelect list1;
		
		protected System.Web.UI.WebControls.Button button3;
		
		protected System.Web.UI.WebControls.Button button4;
		
		protected System.Web.UI.WebControls.Button button5;
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.HtmlControls.HtmlSelect ram;
		
		protected System.Web.UI.HtmlControls.HtmlSelect drive;
		
		protected System.Web.UI.HtmlControls.HtmlSelect cpu;
		
		protected System.Web.UI.HtmlControls.HtmlSelect monitor;
		
		protected System.Web.UI.HtmlControls.HtmlSelect os;
		
		protected System.Web.UI.HtmlControls.HtmlSelect sound;
		
		protected System.Web.UI.WebControls.Button button20;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl price_spot;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl sel;
	}
}
