//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store_part3 {
	
	
	public partial class orders {
		
		protected System.Web.UI.HtmlControls.HtmlForm form9;
		
		protected System.Web.UI.WebControls.Button button14;
		
		protected System.Web.UI.WebControls.Button button15;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl display;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl products;
		
		protected System.Web.UI.HtmlControls.HtmlForm myForm;
		
		protected System.Web.UI.HtmlControls.HtmlInputText user1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText psw;
		
		protected System.Web.UI.WebControls.Button button8;
		
		protected System.Web.UI.HtmlControls.HtmlForm form6;
		
		protected System.Web.UI.WebControls.Button button7;
		
		protected System.Web.UI.WebControls.Button button13;
		
		protected System.Web.UI.HtmlControls.HtmlForm signForm1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText user2;
		
		protected System.Web.UI.HtmlControls.HtmlInputText psw2;
		
		protected System.Web.UI.HtmlControls.HtmlInputText psw3;
		
		protected System.Web.UI.WebControls.Button button9;
		
		protected System.Web.UI.HtmlControls.HtmlForm forgot;
		
		protected System.Web.UI.HtmlControls.HtmlInputText user4;
		
		protected System.Web.UI.HtmlControls.HtmlInputControl email;
		
		protected System.Web.UI.WebControls.Button button18;
		
		protected System.Web.UI.WebControls.Button button12;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl error;
	}
}
