//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store_part3 {
	
	
	public partial class product {
		
		protected System.Web.UI.HtmlControls.HtmlAnchor image;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl name;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl des;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button button3;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl price_spot;
	}
}
